version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["80:95:cc:46:dc:cf:c0:8a:03:8c:f3:d7:aa:9e:35:47"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible 
            export ANSIBLE_HOST_KEY_CHECKING=False
      - run:
          name: Configure server
          working_directory: ./.circleci/ansible
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False 
            export host_key_checking=False
            export record_host_keys=False
            cat inventory.txt
            ansible-playbook -i inventory.txt deploy-backend.yml -vv

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure