version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["a4:c1:95:1e:53:d7:70:94:74:75:31:0f:60:96:52:2f"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible 
      - run:
          name: Configure server
          command: |
            ansible-playbook playbook.yml -i inventory.txt

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure